use_frameworks!

platform :ios, '13.0'

target 'EaseChatUIKit_Example' do
  pod 'chat-uikit', :path => '../'
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
          config.build_settings["DEVELOPMENT_TEAM"] = "JC854K845H"
        end
      end
    end
    # Only for dev debug before AgoraChat_iOS 1.3.0 released.
    system("python3", "Download_Agora_Chat.py", "https://downloadsdk.easemob.com/downloads/AgoraChat/AgoraChat1_3_0.zip")
  end
end
